### ISSUE TITLE
libpng warning: Image height is zero in IHDR

### ISSUE THREAD

**Issue by Nexxo11** [grunt-lucas/porytiles#48]
**Describe the bug**
I'm encountering a libpng warning: Image height is zero in IHDR when trying to compile a secondary tileset using Porytiles. This error seems to indicate that one of the images being processed has a height of zero pixels, which could suggest the image is corrupt or malformed.

**Additional context**
Please include:
- porytiles compile-secondary   /mnt/c/Users/Usuario/Documents/Decomp/porytiles/tiles/city   /mnt/c/Users/Usuario/Documents/Decomp/pokeemerald-expansion/data/tilesets/secondary/city_tiles   /mnt/c/Users/Usuario/Documents/Decomp/pokeemerald-expansion/include/constants/metatile_behaviors.h \

**Environment (please complete the following information):**
 - OS [Windows 11 using wsl]
 - Porytiles release version: if applicable [1.0.0]
 - 
![image](https://github.com/grunt-lucas/porytiles/assets/163916851/b459a657-45ef-4a02-84ec-b1668c34b05f)

**Comment by grunt-lucas** [comment]
`/mnt/c/Users/Usuario/Documents/Decomp/pokeemerald-expansion/data/tilesets/secondary/city_tiles`

If this is your paired primary tileset, it needs to be a Porytiles-format tileset. Unfortunately you cannot currently use compiled Porymap-format tilesets for the paired primary. This is possibly why you are seeing that error message.

I am planning on adding the ability to use a compiled Porymap-format tileset as the paired primary, that's tracked in #47
